#!/usr/bin/Rscript

library(tidyverse)
library(DBI)
library(RSQLite)

if (!exists('con_sqlite')) {
  con_sqlite <- dbConnect(RSQLite::SQLite(), "skillscapes.sqlite")
}

source('common_aggregate_nuts.R')

region_lookup <- tribble(
  ~region, ~geo,
  "ATTIKI", "EL30",
  "FORMER PERFECTURE OF DODEKANISOS", "EL421",
  "FORMER PERFECTURE OF KYKLADES", "EL422",
  "REGIONAL UNIT OF SPORADES", "EL613b",
  "REGIONAL UNIT OF ACHAIA", "EL632",
  "REGIONAL UNIT OF AITOLOAKARNANIA", "EL631",
  "REGIONAL UNIT OF ARGOLIDA", "EL651a",
  "REGIONAL UNIT OF ARKADIA", "EL651b",
  "REGIONAL UNIT OF ARTA", "EL541a",
  "REGIONAL UNIT OF CHALKIDIKI", "EL527",
  "REGIONAL UNIT OF CHANIA", "EL434",
  "REGIONAL UNIT OF CHIOS", "EL413",
  "REGIONAL UNIT OF DRAMA", "EL514",
  "REGIONAL UNIT OF EVROS", "EL511",
  "REGIONAL UNIT OF EVRYTANIA", "EL643",
  "REGIONAL UNIT OF EVVOIA", "EL642",
  "REGIONAL UNIT OF FLORINA", "EL533",
  "REGIONAL UNIT OF FOKIDA", "EL645",
  "REGIONAL UNIT OF FTHIOTIDA", "EL644",
  "REGIONAL UNIT OF GREVENA", "EL531a",
  "REGIONAL UNIT OF IKARIA", "EL412a",
  "REGIONAL UNIT OF ILEIA", "EL633",
  "REGIONAL UNIT OF IMATHIA", "EL521",
  "REGIONAL UNIT OF IOANNINA", "EL543",
  "REGIONAL UNIT OF IRAKLIO", "EL431",
  "REGIONAL UNIT OF ITHAKI", "EL623a",
  "REGIONAL UNIT OF KARDITSA", "EL611a",
  "REGIONAL UNIT OF KASTORIA", "EL532",
  "REGIONAL UNIT OF KAVALA", "EL515b",
  "REGIONAL UNIT OF KAVALA & THASOS", "EL515",
  "REGIONAL UNIT OF KEFALLINIA", "EL623b",
  "REGIONAL UNIT OF KEFALLINIA & ITHAKI", "EL623",
  "REGIONAL UNIT OF KERKYRA", "EL622",
  "REGIONAL UNIT OF KILKIS", "EL523",
  "REGIONAL UNIT OF KORINTHIA", "EL652",
  "REGIONAL UNIT OF KOZANI", "EL531b",
  "REGIONAL UNIT OF LAKONIA", "EL653a",
  "REGIONAL UNIT OF LARISA", "EL612",
  "REGIONAL UNIT OF LASITHI", "EL432",
  "REGIONAL UNIT OF LEFKADA", "EL624",
  "REGIONAL UNIT OF LESVOS", "EL411a",
  "REGIONAL UNIT OF LESVOS & LIMNOS", "EL411",
  "REGIONAL UNIT OF LIMNOS", "EL411b",
  "REGIONAL UNIT OF MAGNISIA", "EL613a",
  "REGIONAL UNIT OF MAGNISIA & SPORADES", "EL613",
  "REGIONAL UNIT OF MESSINIA", "EL653b",
  "REGIONAL UNIT OF PELLA", "EL524",
  "REGIONAL UNIT OF PIERIA", "EL525",
  "REGIONAL UNIT OF PREVEZA", "EL541b",
  "REGIONAL UNIT OF RETHYMNO", "EL433",
  "REGIONAL UNIT OF RODOPI", "EL513",
  "REGIONAL UNIT OF SAMOS", "EL412b",
  "REGIONAL UNIT OF SAMOS & IKARIA", "EL412",
  "REGIONAL UNIT OF SERRES", "EL526",
  "REGIONAL UNIT OF THASOS", "EL515a",
  "REGIONAL UNIT OF THESPROTIA", "EL542",
  "REGIONAL UNIT OF THESSALONIKI", "EL522",
  "REGIONAL UNIT OF TRIKALA", "EL611b",
  "REGIONAL UNIT OF VOIOTIA", "EL641",
  "REGIONAL UNIT OF XANTHI", "EL512",
  "REGIONAL UNIT OF ZAKYNTHOS", "EL621",
  "REGIONAL UNIT OF ANDROS", "EL422a",
  "REGIONAL UNIT OF NORTH ATHENS", "EL301",
  "REGIONAL UNIT OF WEST ATTICA", "EL306",
  "REGIONAL UNIT OF EAST ATTICA", "EL305",
  "REGIONAL UNIT OF WEST ATHENS", "EL302",
  "REGIONAL UNIT OF SOUTH ATHENS", "EL304",
  "REGIONAL UNIT OF THIRA", "EL422b",
  "REGIONAL UNIT OF KALYMNOS", "EL421a",
  "REGIONAL UNIT OF KARPATHOS & KASOS", "EL421b",
  "REGIONAL UNIT OF KEA", "EL422c",
  "REGIONAL UNIT OF KOS", "EL421c",
  "REGIONAL UNIT OF MILOS", "EL422d",
  "REGIONAL UNIT OF MYKONOS", "EL422e",
  "REGIONAL UNIT OF NAXOS", "EL422f",
  "REGIONAL UNIT OF PAROS", "EL422g",
  "REGIONAL UNIT OF RHODES", "EL421d",
  "REGIONAL UNIT OF SYROS", "EL422h",
  "REGIONAL UNIT OF TINOS", "EL422i",
  "REGIONAL UNIT OF CENTRAL ATHENS", "EL303",
  "REGIONAL UNIT OF PIRAIUS", "EL307a",
  "REGIONAL UNIT OF ISLANDS", "EL307b"
)

d <- read_csv("ELSTAT/population_by_region.csv") |>
  left_join(region_lookup, by="region") |>
  select(-region) |>
  relocate(geo, .before=everything()) |>
  mutate(year = as.integer(year))

check_for_NAs(d, "geo")

d_nuts3 <- aggregate_regional_to_nuts3(d, geo, year) |>
  rows_upsert(d, by=c("geo", "year"))
d_nuts2 <- aggregate_nuts3_to_nuts2(d_nuts3, geo, year)
d_nuts1 <- aggregate_nuts2_to_nuts1(d_nuts2, geo, year)
d_population <- rbind(d_nuts1, d_nuts2, d_nuts3)

dbWriteTable(con_sqlite, "gr_population", d, overwrite = TRUE)
